AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFront Distribution and Route53 Records for ksc.asia

Parameters:
  DomainName:
    Type: String
    Default: ksc.asia
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for ksc.asia
  AmplifyDistributionDomainName:
    Type: String
    Description: AmplifyDistributionDomainName
  AppSyncDomainName:
    Type: String
    Description: pzjdggifqfetjp3vr6awpcqtcq.appsync-api.ap-northeast-1.amazonaws.com
  CertificateArn:
    Type: String
    Description: ACM証明書のARN（us-east-1のもの）

Resources:

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"
        DefaultRootObject: index.html
        Origins:
          - Id: AmplifyOrigin
            DomainName: !Ref AmplifyDistributionDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only

          - Id: AppSyncOrigin
            DomainName: !Ref AppSyncDomainName
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only

        DefaultCacheBehavior:
          TargetOriginId: AmplifyOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

        CacheBehaviors:
          - PathPattern: graphql
            TargetOriginId: AppSyncOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0

        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

  Route53RecordRoot:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  Route53RecordWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
