AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFront Distribution and Route53 Records for ksc.asia

Parameters:
  DomainName:
    Type: String
    Default: ksc.asia
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for ksc.asia
  AmplifyDistributionDomainName:
    Type: String
    Description: AmplifyDistributionDomainName
  CertificateArn:
    Type: String
    Description: ACM証明書のARN（us-east-1のもの）

Resources:

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"
        DefaultRootObject: index.html
        Origins:
          - Id: AmplifyOrigin
            DomainName: !Ref AmplifyDistributionDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: AmplifyOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

  Route53RecordRoot:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront固定

  Route53RecordWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
